### ISSUE TITLE
Failed to run, module load errors

### ISSUE THREAD

**Issue by whyrusleeping** [haadcode/orbit#191]
```
whyrusleeping@aredhel ~/c/orbit (master)> npm run start

> orbit@3.2.0 start /home/whyrusleeping/code/orbit
> npm run electron


> orbit@3.2.0 electron /home/whyrusleeping/code/orbit
> electron .

2016-11-26T07:16:47.043Z [DEBUG] Orbit.Index-Native: Run index.js in 'debug' mode
2016-11-26T07:16:47.126Z [DEBUG] ipfs-daemon: Initializing IPFS daemon
2016-11-26T07:16:47.127Z [DEBUG] ipfs-daemon: Using IPFS repo at '/home/whyrusleeping/.config/orbit/ipfs'
2016-11-26T07:16:47.715Z [DEBUG] ipfs-daemon: Starting IPFS daemon
2016-11-26T07:16:49.734Z [ERROR] Orbit.Index-Native: { Error: Cannot find module 'lodash/_overRest'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/whyrusleeping/code/orbit/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/whyrusleeping/code/orbit/node_modules/ipfs-api/node_modules/async/internal/rest.js:8:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12) code: 'MODULE_NOT_FOUND' }
2016-11-26T07:16:49.735Z [ERROR] ipfs-daemon: { Error: Cannot find module 'lodash/_overRest'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/whyrusleeping/code/orbit/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/whyrusleeping/code/orbit/node_modules/ipfs-api/node_modules/async/internal/rest.js:8:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12) code: 'MODULE_NOT_FOUND' }
```

At commit 9f12c7499841e740373536fcb036936eeca108d0 after a fresh npm install

**Comment by haadcode** [comment]
@whyrusleeping can you do a fresh clone from master and run `make` and follow the instructions from thereon? I think I've fixed the issues. 

Check out the cool new configuration screen (in the login screen) where you can customize the IPFS instance that orbit runs :)

**Comment by whyrusleeping** [comment]
@haadcode cool, looks like thats working now :)

Only problem now is that i'm seeing zero peers connected...

**Comment by haadcode** [comment]
Great to hear! I'm gonna close this one then.

The 0 peers is a known issue, opened an issue to make sure it gets fixed: https://github.com/haadcode/orbit/issues/195
