### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by asbjornenge** [haadcode/orbit#32]
Hi! I'm trying to start orbit, but keep getting:

```
❯ node index.js 
2016-05-25T12:57:43.573Z [DEBUG] Orbit.Main: Running in 'release' mode
2016-05-25T12:57:43.575Z [INFO]  Orbit.Main: Starting IPFS...
2016-05-25T12:57:43.576Z [DEBUG] ipfs-daemon: Starting IPFS daemon
2016-05-25T12:57:43.576Z [DEBUG] ipfs-daemon: Using IPFS data directory: '/home/asbjorn/.ipfs', exists: true
2016-05-25T12:57:45.588Z [ERROR] Orbit.Main: Client request error: read ECONNRESET
2016-05-25T12:57:45.588Z [ERROR] Orbit.Main: Stack trace:
 Error: read ECONNRESET
    at exports._errnoException (util.js:893:11)
    at TCP.onread (net.js:555:26)
```

I can telnet the ip and port in `network.json`.

**Comment by haadcode** [comment]
Hey @asbjornenge, thanks for reporting the bug. Due to things being in flux, master might not work at the moment. I expect it to be fully working again next week. Meanwhile, if you're looking to try out Orbit, see https://github.com/haadcode/orbit/tree/js-ipfs.

**Comment by asbjornenge** [comment]
Thanks! I can wait until things have calmed down :wink: Would appreciate a :wave: either on this issue or on twitter or something when it's ready for another try :+1:

**Comment by haadcode** [comment]
This should be fixed now in master. Let me know if you still run into this problem, or any other.
